// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package go_micro_src_consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_ef5791303895afaf, []int{0}
}
func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (dst *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(dst, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_ef5791303895afaf, []int{1}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_ef5791303895afaf, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_ef5791303895afaf, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.src.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.src.consignment.Container")
	proto.RegisterType((*GetRequest)(nil), "go.micro.src.consignment.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.src.consignment.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ShippingService service

type ShippingServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error)
	GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type shippingServiceClient struct {
	c           client.Client
	serviceName string
}

func NewShippingServiceClient(serviceName string, c client.Client) ShippingServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.src.consignment"
	}
	return &shippingServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ShippingService.CreateConsignment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ShippingService.GetConsignments", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippingService service

type ShippingServiceHandler interface {
	CreateConsignment(context.Context, *Consignment, *Response) error
	GetConsignments(context.Context, *GetRequest, *Response) error
}

func RegisterShippingServiceHandler(s server.Server, hdlr ShippingServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ShippingService{hdlr}, opts...))
}

type ShippingService struct {
	ShippingServiceHandler
}

func (h *ShippingService) CreateConsignment(ctx context.Context, in *Consignment, out *Response) error {
	return h.ShippingServiceHandler.CreateConsignment(ctx, in, out)
}

func (h *ShippingService) GetConsignments(ctx context.Context, in *GetRequest, out *Response) error {
	return h.ShippingServiceHandler.GetConsignments(ctx, in, out)
}

func init() { proto.RegisterFile("consignment.proto", fileDescriptor_consignment_ef5791303895afaf) }

var fileDescriptor_consignment_ef5791303895afaf = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x49, 0xff, 0xe7, 0x52, 0x51, 0xd5, 0x03, 0x58, 0x30, 0x10, 0x05, 0x90, 0x3a, 0x65,
	0x28, 0x8f, 0x90, 0xa1, 0xca, 0xea, 0xce, 0x08, 0x8a, 0x73, 0x4a, 0x2d, 0x11, 0x3b, 0xd8, 0x6e,
	0x79, 0x35, 0x78, 0x0d, 0x9e, 0x08, 0xd5, 0x69, 0xa8, 0x11, 0x2a, 0xea, 0x96, 0xdf, 0x9d, 0xbf,
	0xcb, 0xe7, 0x93, 0x61, 0xca, 0x95, 0x34, 0xa2, 0x94, 0x15, 0x4a, 0x9b, 0xd6, 0x5a, 0x59, 0x45,
	0x68, 0xa9, 0xd2, 0x4a, 0x70, 0xad, 0x52, 0xa3, 0x79, 0xea, 0xf5, 0x93, 0xcf, 0x00, 0xa2, 0xec,
	0x90, 0xc9, 0x39, 0x74, 0x44, 0x41, 0x83, 0x38, 0x98, 0x85, 0xac, 0x23, 0x0a, 0x12, 0x43, 0x54,
	0xa0, 0xe1, 0x5a, 0xd4, 0x56, 0x28, 0x49, 0x3b, 0xae, 0xe1, 0x97, 0xc8, 0x05, 0x0c, 0xde, 0x51,
	0x94, 0x6b, 0x4b, 0xbb, 0x71, 0x30, 0xeb, 0xb3, 0x7d, 0x22, 0x19, 0x00, 0x57, 0xd2, 0xae, 0x84,
	0x44, 0x6d, 0x68, 0x2f, 0xee, 0xce, 0xa2, 0xf9, 0x6d, 0x7a, 0x4c, 0x24, 0xcd, 0xda, 0xb3, 0xcc,
	0xc3, 0xc8, 0x35, 0x84, 0x5b, 0x34, 0x06, 0x5f, 0x9f, 0x44, 0x41, 0xfb, 0xee, 0xe7, 0xa3, 0xa6,
	0x90, 0x17, 0x49, 0x05, 0xe1, 0x0f, 0xf5, 0x47, 0xfc, 0x06, 0x22, 0xbe, 0x31, 0x56, 0x55, 0xa8,
	0x77, 0x6c, 0x23, 0x0e, 0x6d, 0x29, 0x2f, 0x76, 0xde, 0x4a, 0x8b, 0x52, 0x48, 0xe7, 0x1d, 0xb2,
	0x7d, 0x22, 0x97, 0x30, 0xdc, 0x98, 0x06, 0xea, 0x35, 0x8d, 0x5d, 0xcc, 0x8b, 0x64, 0x0c, 0xb0,
	0x40, 0xcb, 0xf0, 0x6d, 0x83, 0xc6, 0x26, 0x1f, 0x01, 0x8c, 0x18, 0x9a, 0x5a, 0x49, 0x83, 0x84,
	0xc2, 0x90, 0x6b, 0x5c, 0x59, 0x6c, 0x0c, 0x46, 0xac, 0x8d, 0x64, 0x01, 0x91, 0x77, 0x4b, 0xa7,
	0x11, 0xcd, 0xef, 0xff, 0x5d, 0x43, 0xfb, 0xcd, 0x7c, 0x92, 0xe4, 0x30, 0xf6, 0xa2, 0xa1, 0x5d,
	0xb7, 0xd0, 0x13, 0x27, 0xfd, 0x42, 0xe7, 0x5f, 0x01, 0x4c, 0x96, 0x6b, 0x51, 0xd7, 0x42, 0x96,
	0x4b, 0xd4, 0x5b, 0xc1, 0x91, 0x3c, 0xc3, 0x34, 0x73, 0xca, 0xfe, 0x63, 0x38, 0x6d, 0xfa, 0x55,
	0x72, 0xfc, 0x58, 0xbb, 0xa1, 0xe4, 0x8c, 0x3c, 0xc2, 0x64, 0x81, 0xd6, 0xe3, 0x0c, 0xb9, 0x3b,
	0x0e, 0x1e, 0x36, 0x7d, 0xda, 0xf8, 0x97, 0x81, 0x7b, 0xe9, 0x0f, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x38, 0xc3, 0x8c, 0xfe, 0x02, 0x00, 0x00,
}
